### ISSUE TITLE
Have problem after epoch 50.

### ISSUE THREAD

**Issue by seta-quynhbui** [NVlabs/few-shot-vid2vid#18]
After notification : "---------- Now start training multiple frames -------------"
i wait approximately 12 hours, but it do not run to next epoch. Can you explain this problem. i run on AWS instance have 2 GPU Tesla M60 8gb.

**Comment by justfouw** [comment]
@seta-quynhbui I encounter similar situations like you.  It seems that the training is stuck at epoch 83. I am also looking forward to some suggestion.

**Comment by howardgriffin** [comment]
> After notification : "---------- Now start training multiple frames -------------"
> i wait approximately 12 hours, but it do not run to next epoch. Can you explain this problem. i run on AWS instance have 2 GPU Tesla M60 8gb.

Same issue

**Comment by chenwq-bjtu** [comment]
I have the same problem. it cannot pass epoch 50,  when running continue train, the server will reboot always. It seems memory(8GB) of Nvidia(GeForce RTX 2080) reaching full, the system reboots. I already use --batchSize 1 for low memory using.

**Comment by scarymrgrey** [comment]
The same issue. Did somebody find a solution?

**Comment by chenwq-bjtu** [comment]
> I have the same problem. it cannot pass epoch 50, when running continue train, the server will reboot always. It seems memory(8GB) of Nvidia(GeForce RTX 2080) reaching full, the system reboots. I already use --batchSize 1 for low memory using.

I fix the problem by setting GPU limit power,  it seems that the machine provides no enough power.
But when i test the model after 50 epoch, such as 55, 60 epoch, the synthesized result is worse than epoch 50.  Please give me some suggestion  or guideline。

test by epoch 60
![image](https://user-images.githubusercontent.com/22881484/71790668-9c978b80-306c-11ea-94d3-81c558c4c5df.png)

test by epoch 50
![image](https://user-images.githubusercontent.com/22881484/71790690-ae792e80-306c-11ea-8021-bb5cebde8fe7.png)

**Comment by tbbjymm21** [comment]
> I have the same problem. it cannot pass epoch 50, when running continue train, the server will reboot always. It seems memory(8GB) of Nvidia(GeForce RTX 2080) reaching full, the system reboots. I already use --batchSize 1 for low memory using.
> 
> I fix the problem by setting GPU limit power,  it seems that the machine provides no enough power.
> But when i test the model after 50 epoch, such as 55, 60 epoch, the synthesized result is worse than epoch 50.  Please give me some suggestion  or guideline。
> test by epoch 60
> 
> test by epoch 50

What's your mailbox?I want to ask a question privately, and can we discuss it together?

**Comment by BaldrLector** [comment]
> > I have the same problem. it cannot pass epoch 50, when running continue train, the server will reboot always. It seems memory(8GB) of Nvidia(GeForce RTX 2080) reaching full, the system reboots. I already use --batchSize 1 for low memory using.
> 
> I fix the problem by setting GPU limit power, it seems that the machine provides no enough power.
> But when i test the model after 50 epoch, such as 55, 60 epoch, the synthesized result is worse than epoch 50. Please give me some suggestion or guideline。
> 
> test by epoch 60
> ![image](https://user-images.githubusercontent.com/22881484/71790668-9c978b80-306c-11ea-94d3-81c558c4c5df.png)
> 
> test by epoch 50
> ![image](https://user-images.githubusercontent.com/22881484/71790690-ae792e80-306c-11ea-8021-bb5cebde8fe7.png)

Hi, chenwq-bjtu.
I face the same problem as you.
Here are my results of epoch 55,
![image](https://user-images.githubusercontent.com/19874480/71864577-1ac26380-313b-11ea-9307-fd5386e598b0.png)
![image](https://user-images.githubusercontent.com/19874480/71864594-27df5280-313b-11ea-9391-7a7d0ca8d4ea.png)

and epoch 80
![image](https://user-images.githubusercontent.com/19874480/71865020-86f19700-313c-11ea-9547-a4fe2dc9e61a.png)
![image](https://user-images.githubusercontent.com/19874480/71865042-9375ef80-313c-11ea-9d36-8e69d089b0e0.png)

Clearly, the epoch 80 results have more artifacts.

And I guess some reason the bad result:

1. the first 50 epochs are training with one-frame then training with time series in the next epoch. You may use --finetune_all to update the single generator continually ( as my experiment, for now, it seems  do not work)
In fact, the longer the sequence, the more the landmarks deviate from the first frame, which calls for more epochs to optimize the method. For now, I have not yet finished the training.

2. check your GAN loss, it's maybe collapsed.

3. considering you only use 1 GeForce RTX 2080 and use batchSize =1, its seems you should reduce the learning rate and increasing the niter_single

I don't completely reimplement the result of the paper, watching your info

**Comment by chenwq-bjtu** [comment]
Thank you for your answers:
1) here is my GAN loss, is it collapsed? 
2) i use default learning rate 0.0004, which i think it may be well, if reduce,  my train will be slower
![image](https://user-images.githubusercontent.com/22881484/71881041-82dd6d80-316c-11ea-822b-7b1613e4660d.png)

By the way, your testing result looks like better enough.  Well done!

**Comment by BaldrLector** [comment]
@chenwq-bjtu 

1. In fact, I can't know if the GAN is collapsed just from few loss prints, you may need to check your loss log ( the author gives Tensorboard record using option --tf_log, or you could also refine the code and use visdom ).
Generally, if the training is normal, you should see the G_GAN and D loss are balance (almost unchanged) during training, and G_VGG, F_Flow are reducing.

2. It is fine to use 0.0004 if it works for you, but generally mini batchSize 1 should use a lower learning rate. I use 0.0002 for batchSize=12

**Comment by chenwq-bjtu** [comment]
@BaldrLector 
Here is testing result with 80 epoch training model, It seems has problem。Because of my machine power and requirement to check the train result,  the training progress has been interrupted many times。Does it make the model collapsed？How can I train from the middle epoch？
![image](https://user-images.githubusercontent.com/22881484/72305955-6b443e80-36b0-11ea-8d67-eea04a9aad2c.png)

Or can you supply your working model, then we can use the model to do next step working.

**Comment by wangchao0899** [comment]
/content/gdrive/My Drive/few-shot-vid2vid
CustomDatasetDataLoader
8 sequences
dataset [FaceDataset] was created
Resuming from epoch 51 at iteration 0
Downloading: "https://download.pytorch.org/models/vgg19-dcbb9e9d.pth" to /root/.cache/torch/checkpoints/vgg19-dcbb9e9d.pth
100% 548M/548M [00:26<00:00, 21.8MB/s]
---------- Networks initialized -------------
---------- Optimizers initialized -------------
update learning rate: 0.000400 -> 0.000040
---------- Now start training multiple frames -------------
Pretrained network G has fewer layers; The following are not initialized:
['flow_network_temp.conv_flow', 'flow_network_temp.conv_w', 'flow_network_temp.down_flow', 'flow_network_temp.res_flow', 'flow_network_temp.up_flow', 'img_prev_embedding.conv_first', 'img_prev_embedding.down_0', 'img_prev_embedding.down_1', 'img_prev_embedding.down_2', 'img_prev_embedding.down_3', 'img_prev_embedding.down_4', 'img_prev_embedding.up_0', 'img_prev_embedding.up_1', 'img_prev_embedding.up_2', 'img_prev_embedding.up_3', 'img_prev_embedding.up_4']
network loaded from ./checkpoints/face/latest_net_D.pth
./checkpoints/face/latest_net_DT.pth not exists yet!
model [Vid2VidModel] was created
update learning rate: 0.000040 -> 0.000039
--- Updating training sequence length to 4 ---
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:2506: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:2705: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "
Traceback (most recent call last):
  File "train.py", line 73, in <module>
    train()
  File "train.py", line 54, in train
    g_losses, generated, data_prev = model(data_list_t, save_images=trainer.save, mode='generator')
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/gdrive/My Drive/few-shot-vid2vid/models/models.py", line 90, in forward
    outputs = self.model(*inputs, **kwargs, dummy_bs=self.pad_bs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/gdrive/My Drive/few-shot-vid2vid/models/vid2vid_model.py", line 47, in forward
    prevs, flow_gt, conf_gt)
  File "/content/gdrive/My Drive/few-shot-vid2vid/models/vid2vid_model.py", line 81, in forward_generator
    loss_G_VGG = self.lossCollector.compute_VGG_losses(fake_image, fake_raw_image, tgt_image, fg_mask_union)        
  File "/content/gdrive/My Drive/few-shot-vid2vid/models/loss_collector.py", line 125, in compute_VGG_losses
    loss_G_VGG = self.criterionVGG(fake_image, tgt_image) * opt.lambda_vgg
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/gdrive/My Drive/few-shot-vid2vid/models/networks/loss.py", line 127, in forward
    loss = self.compute_loss(x_vgg, y_vgg)
  File "/content/gdrive/My Drive/few-shot-vid2vid/models/networks/loss.py", line 117, in compute_loss
    loss += self.weights[i] * self.criterion(x_vgg[i], y_vgg[i].detach())        
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py", line 88, in forward
    return F.l1_loss(input, target, reduction=self.reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2191, in l1_loss
    ret = torch._C._nn.l1_loss(expanded_input, expanded_target, _Reduction.get_enum(reduction))
RuntimeError: CUDA out of memory. Tried to allocate 160.00 MiB (GPU 0; 15.90 GiB total capacity; 15.09 GiB already allocated; 23.88 MiB free; 15.16 GiB reserved in total by PyTorch)

**Comment by swpucl** [comment]
> > I have the same problem. it cannot pass epoch 50, when running continue train, the server will reboot always. It seems memory(8GB) of Nvidia(GeForce RTX 2080) reaching full, the system reboots. I already use --batchSize 1 for low memory using.
> 
> I fix the problem by setting GPU limit power, it seems that the machine provides no enough power.
> But when i test the model after 50 epoch, such as 55, 60 epoch, the synthesized result is worse than epoch 50. Please give me some suggestion or guideline。
> 
> test by epoch 60
> ![image](https://user-images.githubusercontent.com/22881484/71790668-9c978b80-306c-11ea-94d3-81c558c4c5df.png)
> 
> test by epoch 50
> ![image](https://user-images.githubusercontent.com/22881484/71790690-ae792e80-306c-11ea-8021-bb5cebde8fe7.png)
I get the result 11 epoch,like this:
![image](https://user-images.githubusercontent.com/29971414/100691034-c7947780-33c2-11eb-980a-c1bc3e39a59c.png)
That's correct?

**Comment by tcwang0509** [comment]
This repo is now deprecated. Please refer to the new Imaginaire repo: https://github.com/NVlabs/imaginaire.
